-- Enable UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- 1. WATCHLISTS
create table if not exists public.watchlists (
    id bigint generated by default as identity primary key,
    user_id text default 'default',
    ticker text not null,
    company_name text,
    notes text,
    target_price numeric,
    added_at timestamptz default now(),
    
    unique(user_id, ticker)
);

-- 2. MEMOS
create table if not exists public.memos (
    id bigint generated by default as identity primary key,
    user_id text default 'default',
    ticker text not null,
    thesis text,
    drivers text,
    risks text,
    catalysts text,
    buy_conditions text,
    notes text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    
    unique(user_id, ticker)
);

-- 3. SNAPSHOTS (Historical Data)
create table if not exists public.snapshots (
    id bigint generated by default as identity primary key,
    ticker text not null,
    snapshot_date date default current_date,
    current_price numeric,
    fair_value_dcf numeric,
    scorecard numeric,
    mos_dcf numeric,
    verdict text,
    piotroski int,
    altman_z numeric,
    pe numeric,
    insider_signal numeric,
    data jsonb, -- flexible storage for extra fields
    created_at timestamptz default now()
);

-- 4. ALERTS
create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    user_id text default 'default',
    ticker text not null,
    alert_type text not null, -- 'price_below', 'price_above', 'scorecard_change'
    threshold numeric,
    is_active boolean default true,
    created_at timestamptz default now(),
    triggered_at timestamptz
);

-- 5. AI REPORTS CACHE
create table if not exists public.ai_reports (
    id bigint generated by default as identity primary key,
    ticker text not null,
    report_data jsonb,
    model_used text,
    created_at timestamptz default now()
);

-- 6. PORTFOLIO
create table if not exists public.portfolio (
    id bigint generated by default as identity primary key,
    user_id text default 'default',
    ticker text not null,
    shares numeric default 0,
    buy_price numeric,
    buy_date date default current_date,
    created_at timestamptz default now()
);

-- Row Level Security (RLS) - Optional: Enable if you want public access control
-- alter table public.watchlists enable row level security;
-- create policy "Enable read access for all users" on public.watchlists for select using (true);
-- (For this app using a service role or single user, RLS is often skipped or set to public for simplicity in prototyping)
